services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src

  db:
    image: postgres:16.0-bookworm
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 1s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    restart: always
    ports:
     - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      -  /app/node_modules
    environment:
      - WATCHPACK_POLLING=true

volumes:
  pgdata:
