services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src

  db:
    image: postgres:16.0-bookworm
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      -  /app/node_modules
    environment:
      - WATCHPACK_POLLING=true

volumes:
  pgdata:
