version: '3.8'

services:
  transcendence:
    build: ./transcendence
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - ./transcendence/app:/app/app
      - ./transcendence/api:/app/api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      DJANGO_SUPERUSER: ${DJANGO_SUPERUSER}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASS: ${DJANGO_SUPERUSER_PASS}

  db:
    image: postgres:16.0-bookworm
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
