services:
  transcendence:
    build: ./transcendence
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./transcendence/app:/app/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

  db:
    image: postgres:16.0-bookworm
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata:
