services:
  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - 127.0.0.1:8080:5000
    volumes:
      - ./backend/src:/app/src
  postgres:
    image: postgres:bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports: 3001:3001
    volumes:
      - ./frontend/src:/app/src
    image: react-image
volumes:
  pgdata:
